Models/Devices.cs
using System;
using System.ComponentModel.DataAnnotations;
using MvcDevices.Data;
using IPGeolocation;

namespace MvcDevices.Models
{
    public class Devices
    {
        [Key]
        public int AssetID { get; set; }
        public string AssetName { get; set; }
        public string PublicIP { get; set; }
        public string PrivateIP { get; set; }
        public bool ConnectionStatus { get; set; }
        public int PrivilegeID { get; set; }
        public string Hostname { get; set; }
        public int ProjectID { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Project_APATE.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/Devices1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcDevices.Models;
using MvcDevices.Data;
using IPGeolocation;
using Project_APATE.Models;

namespace Project_APATE.Controllers
{
    public class Devices1Controller : Controller
    {
        private readonly MvcDevicesContext _context;

        public Devices1Controller(MvcDevicesContext context)
        {
            _context = context;
        }

        // GET: Devices1
        public async Task<IActionResult> Index()
        {
            

            return View(await _context.Devices.ToListAsync());
        }

        // GET: Devices1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var devices = await _context.Devices
                .FirstOrDefaultAsync(m => m.AssetID == id);
            if (devices == null)
            {
                return NotFound();
            }

            return View(devices);
        }

        // GET: Devices1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Devices1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AssetID,AssetName,PublicIP,PrivateIP,ConnectionStatus,PrivilegeID,Hostname,ProjectID")] Devices devices)
        {
            if (ModelState.IsValid)
            {
                _context.Add(devices);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(devices);
        }

        // GET: Devices1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var devices = await _context.Devices.FindAsync(id);
            if (devices == null)
            {
                return NotFound();
            }
            return View(devices);
        }

        // POST: Devices1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AssetID,AssetName,PublicIP,PrivateIP,ConnectionStatus,PrivilegeID,Hostname,ProjectID")] Devices devices)
        {
            if (id != devices.AssetID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(devices);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DevicesExists(devices.AssetID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(devices);
        }

        // GET: Devices1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var devices = await _context.Devices
                .FirstOrDefaultAsync(m => m.AssetID == id);
            if (devices == null)
            {
                return NotFound();
            }

            return View(devices);
        }

        // POST: Devices1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var devices = await _context.Devices.FindAsync(id);
            _context.Devices.Remove(devices);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DevicesExists(int id)
        {
            return _context.Devices.Any(e => e.AssetID == id);
        }
    }
}

Controllers/DevicesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace MvcMovie.Controllers
{
    public class DevicesController : Controller
    {
        // 
        // GET: /Devices/

        public IActionResult Index()
        {
            return View();
        }

        // GET: /Devices/Welcome/ 
        // Requires using System.Text.Encodings.Web;
        public IActionResult Welcome(string name, int numTimes = 1)
        {
            ViewData["Message"] = "Hello " + name;
            ViewData["NumTimes"] = numTimes;

            return View();
        }
    }
}

Controllers/GeoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Project_APATE.Controllers
{
    public class GeoController : Controller
{
        // 
        // GET: /HelloWorld/

        public IActionResult Index()
        {
            return View();
        }

        // 
        // GET: /HelloWorld/Welcome/ 

        public IActionResult SplashPage()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Project_APATE.Models;

namespace Project_APATE.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Login()
        {
            return View();
        }
    }
}

Views/Devices/Index.cshtml
@{
    ViewData["Title"] = "Devices";
}

<h2>All Devices</h2>

<p>Hello from our View Template!</p>

Views/Devices1/Create.cshtml
@model MvcDevices.Models.Devices

@{
    ViewData["Title"] = "Create";
}

<h1>Add New Offline Devices</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AssetName" class="control-label"></label>
                <input asp-for="AssetName" class="form-control" />
                <span asp-validation-for="AssetName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublicIP" class="control-label"></label>
                <input asp-for="PublicIP" class="form-control" />
                <span asp-validation-for="PublicIP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrivateIP" class="control-label"></label>
                <input asp-for="PrivateIP" class="form-control" />
                <span asp-validation-for="PrivateIP" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ConnectionStatus" /> @Html.DisplayNameFor(model => model.ConnectionStatus)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="PrivilegeID" class="control-label"></label>
                <input asp-for="PrivilegeID" class="form-control" />
                <span asp-validation-for="PrivilegeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hostname" class="control-label"></label>
                <input asp-for="Hostname" class="form-control" />
                <span asp-validation-for="Hostname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectID" class="control-label"></label>
                <input asp-for="ProjectID" class="form-control" />
                <span asp-validation-for="ProjectID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Devices1/Delete.cshtml
@model MvcDevices.Models.Devices

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Devices</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AssetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AssetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublicIP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublicIP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrivateIP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrivateIP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConnectionStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConnectionStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrivilegeID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrivilegeID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hostname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hostname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AssetID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Devices1/Details.cshtml
@model MvcDevices.Models.Devices

@{
    ViewData["Title"] = "Details";
}

<h1>@Model.AssetName</h1>

<div>
    <h4>Asset Details</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AssetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AssetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublicIP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublicIP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrivateIP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrivateIP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConnectionStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConnectionStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrivilegeID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrivilegeID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hostname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hostname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.AssetID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

<div>
    <h3>Placeholder</h3>
</div>

Views/Devices1/Edit.cshtml
@model MvcDevices.Models.Devices

@{
    ViewData["Title"] = "Edit";
}

<h1>Modify Asset Details</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AssetID" />
            <div class="form-group">
                <label asp-for="AssetName" class="control-label"></label>
                <input asp-for="AssetName" class="form-control" />
                <span asp-validation-for="AssetName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublicIP" class="control-label"></label>
                <input asp-for="PublicIP" class="form-control" />
                <span asp-validation-for="PublicIP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrivateIP" class="control-label"></label>
                <input asp-for="PrivateIP" class="form-control" />
                <span asp-validation-for="PrivateIP" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ConnectionStatus" /> @Html.DisplayNameFor(model => model.ConnectionStatus)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="PrivilegeID" class="control-label"></label>
                <input asp-for="PrivilegeID" class="form-control" />
                <span asp-validation-for="PrivilegeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hostname" class="control-label"></label>
                <input asp-for="Hostname" class="form-control" />
                <span asp-validation-for="Hostname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectID" class="control-label"></label>
                <input asp-for="ProjectID" class="form-control" />
                <span asp-validation-for="ProjectID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Devices1/Index.cshtml
@model IEnumerable<MvcDevices.Models.Devices>

@{
    ViewData["Title"] = "Index";
}
<link href="~/css/bootstrap.min.css" rel="stylesheet" />

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

<h1>All Devices</h1>

<p>
    <a asp-action="Create">Add New Device</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AssetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublicIP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrivateIP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ConnectionStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrivilegeID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hostname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProjectID)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AssetName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublicIP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrivateIP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ConnectionStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrivilegeID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hostname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectID)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.AssetID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.AssetID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.AssetID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Geo/Index.cshtml
@{
    ViewData["Title"] = "Index";
}



<h1>Geo Locator</h1>




<h5>Enter Public IP</h5>

<form action="/action_page.php">
    <label for="fname">Public IP:</label>
    <input type="text" id="Public IP" name="Public IP"><br><br>
    <input type="submit" value="Locate Asset">
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<h1>Select from the Following:</h1>

<div class="row">
    <div class="column">
        <button class="geo" type="button" style="border:none; background: none" onclick="location.href='@Url.Action("Index", "Geo")'"><img src="~/Icons/world-image-on-computer-screen.png" height="300" width="300" /></button>
        <button type="button" style="border:none; background: none" onclick="location.href='@Url.Action("Index", "Devices1")'"><img src="~/Icons/screen-5.png" height="300" width="300" /></button>
        <button type="button" style="border:none; background: none" onclick="location.href='@Url.Action("Index", "Devices1")'"><img src="~/Icons/printer.png" height="300" width="300" /></button>
    </div>
</div>

Views/Home/Login.cshtml
@{
    ViewData["Title"] = "Login";


    Layout = "";

}

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">


<style>

    :root {
        --input-padding-x: 1.5rem;
        --input-padding-y: 0.75rem;
    }
    /*
    .login,
    .image {
      min-height: 100vh;
    }

    .bg-image {
      background-image: url('https://source.unsplash.com/WEQbe2jBg40/600x1200');
      background-size: cover;
      background-position: center;
    }
    */
    .login-heading {
        font-weight: 300;
    }

    .btn-login {
        font-size: 0.9rem;
        letter-spacing: 0.05rem;
        padding: 0.75rem 1rem;
        border-radius: 2rem;
    }

    .form-label-group {
        position: relative;
        margin-bottom: 1rem;
    }

        .form-label-group > input,
        .form-label-group > label {
            padding: var(--input-padding-y) var(--input-padding-x);
            height: auto;
            border-radius: 2rem;
        }

        .form-label-group > label {
            position: absolute;
            top: 0;
            left: 0;
            display: block;
            width: 100%;
            margin-bottom: 0;
            /* Override default `<label>` margin */
            line-height: 1.5;
            color: #42425e;
            cursor: text;
            /* Match the input under the label */
            border: 1px solid transparent;
            border-radius: .25rem;
            transition: all .1s ease-in-out;
        }

        .form-label-group input::-webkit-input-placeholder {
            color: transparent;
        }

        .form-label-group input:-ms-input-placeholder {
            color: transparent;
        }

        .form-label-group input::-ms-input-placeholder {
            color: transparent;
        }

        .form-label-group input::-moz-placeholder {
            color: transparent;
        }

        .form-label-group input::placeholder {
            color: transparent;
        }

        .form-label-group input:not(:placeholder-shown) {
            padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
            padding-bottom: calc(var(--input-padding-y) / 3);
        }

            .form-label-group input:not(:placeholder-shown) ~ label {
                padding-top: calc(var(--input-padding-y) / 3);
                padding-bottom: calc(var(--input-padding-y) / 3);
                font-size: 12px;
                color: #777;
            }

    /* Fallback for Edge
    -------------------------------------------------- */



    }

    /* Fallback for IE
    -------------------------------------------------- */



    .form-label-group input:-ms-input-placeholder {
        color: #777;
    }
    }
</style>


<div class="container-fluid">
    <div class="row no-gutter">

        <div class="col-md-8 col-lg-6">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-md-9 col-lg-8 mx-auto">
                            <h3 class="login-heading mb-4">Welcome to APATE Tracker</h3>
                            <form>
                                <div class="form-label-group">
                                    <input type="email" id="inputEmail" class="form-control" placeholder="Username" required autofocus>
                                    <label for="inputEmail">Email address</label>
                                </div>

                                <div class="form-label-group">
                                    <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
                                    <label for="inputPassword">Password</label>
                                </div>

                                <div class="custom-control custom-checkbox mb-3">
                                    <input type="checkbox" class="custom-control-input" id="customCheck1">
                                    <label class="custom-control-label" for="customCheck1">Remember password</label>
                                </div>
                                <button class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit" onclick="location.href='@Url.Action("Index", "Devices1")'">Sign in</button>
                                <div class="text-center">
                                    <a class="small" href="#">Forgot password?</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - APATE Dashboard</title>



    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!--
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">-->
</head>

<body>
    <header>
        <!--<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 style="background-color: #42425c">-->
            <div class="container">
                <button type="button" style="border:none; background: none" onclick="location.href='https://github.com/JeffBenson/Social-Engineering-Hardware-and-Tools'"><img src="~/Icons/ErgoLogo-1.png" height="25" width="25" /></button>
                <a style="color: #d9d6f6" class="navbar-brand" asp-area="" asp-controller="Devices1" asp-action="Index">APATE Dashboard</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
    </header>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Ergo Security - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>